# Generated by Django 6.0.2 on 2026-02-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Games', 'Games'), ('Other', 'Other')], max_length=50),
        ),
    ]
